import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import {
  Mail, X, Building2,
  ChevronDown, ChevronUp, CheckSquare, Square, Send,
} from 'lucide-react'
import api from '@/lib/api'
import { formatDate } from '@/lib/utils'
import toast from 'react-hot-toast'
import type { WeeklyReport } from '@/types'

interface Props {
  reportId: number
  weekendDate: string
  onClose: () => void
}

/* ── Build a clean plain-text report body ─────────────────────────────────── */
function buildEmailBody(reports: WeeklyReport[], weekendDate: string): string {
  const line  = '─'.repeat(56)
  const thin  = '· · ·'
  const date  = formatDate(weekendDate, 'dd MMMM yyyy')

  let body = ''
  body += `SPR INDIA — WEEKLY ACTIVITY REPORT\n`
  body += `Week Ending: ${date}\n`
  body += `${line}\n\n`

  for (const r of reports) {
    const deptName = r.department?.name?.toUpperCase() ?? 'DEPARTMENT'
    body += `${deptName}\n`
    body += `${line}\n`

    const sorted = r.notes.slice().sort((a, b) => a.order_index - b.order_index)
    if (sorted.length === 0) {
      body += `  (No activity points recorded)\n`
    } else {
      sorted.forEach((note, i) => {
        body += `  ${i + 1}. ${note.content}\n`
      })
    }
    body += `\n${thin}\n\n`
  }

  body += `${line}\n`
  body += `This report was generated by SPR India — Weekly Report System.\n`
  body += `Confidential · For internal distribution only.\n`

  return body
}

/* ── Component ────────────────────────────────────────────────────────────── */
export default function EmailModal({ reportId, weekendDate, onClose }: Props) {
  const [selectedOtherIds, setSelectedOtherIds] = useState<number[]>([])
  const [showOther,        setShowOther]        = useState(false)

  const { data: report } = useQuery<WeeklyReport>({
    queryKey: ['report', reportId],
    queryFn:  () => api.get(`/reports/${reportId}`).then(r => r.data),
  })

  const { data: otherReports = [] } = useQuery<WeeklyReport[]>({
    queryKey: ['published-week', weekendDate],
    queryFn:  () => api.get(`/reports/week/${weekendDate}/published`).then(r => r.data),
    enabled:  !!weekendDate,
  })

  const allSelected: WeeklyReport[] = [
    report,
    ...otherReports.filter(r => selectedOtherIds.includes(r.id)),
  ].filter(Boolean) as WeeklyReport[]

  /* ── Open Outlook directly via mailto: ──────────────────────────────────── */
  const handleOpenOutlook = () => {
    if (!report) return
    const subject = `SPR India — Weekly Activity Report | Week Ending ${formatDate(weekendDate, 'dd MMMM yyyy')}`
    const body    = buildEmailBody(allSelected, weekendDate)
    window.location.href = `mailto:?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`
    toast.success('Outlook is opening with the report pre-filled')
    onClose()
  }

  /* ── Helpers ─────────────────────────────────────────────────────────────── */
  const toggleOther = (id: number) =>
    setSelectedOtherIds(p => p.includes(id) ? p.filter(x => x !== id) : [...p, id])

  /* ── Render ──────────────────────────────────────────────────────────────── */
  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center p-4"
      style={{ background: 'rgba(44,8,32,0.60)', backdropFilter: 'blur(6px)' }}
      onClick={e => { if (e.target === e.currentTarget) onClose() }}
    >
      <div
        className="bg-white w-full max-w-md flex flex-col animate-scale-in"
        style={{
          borderRadius: '1.25rem',
          boxShadow: '0 24px 64px rgba(77,14,56,0.22), 0 4px 16px rgba(0,0,0,0.08)',
          border: '1px solid rgba(77,14,56,0.10)',
          maxHeight: '90vh',
        }}
      >

        {/* ── Header ── */}
        <div className="flex items-center justify-between px-6 py-5"
             style={{ borderBottom: '1px solid #f0ece8', flexShrink: 0 }}>
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl flex items-center justify-center"
                 style={{ background: 'rgba(77,14,56,0.08)' }}>
              <Mail className="w-5 h-5" style={{ color: '#4d0e38' }} />
            </div>
            <div>
              <h2 className="font-display text-xl leading-tight" style={{ color: '#1a1512' }}>
                Send via Outlook
              </h2>
              <p className="text-xs font-medium mt-0.5" style={{ color: '#a89f98' }}>
                Opens Outlook directly with the report pre-filled
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="w-8 h-8 rounded-lg flex items-center justify-center transition-colors"
            style={{ color: '#a89f98' }}
            onMouseEnter={e => { e.currentTarget.style.background = '#f4f2f0'; e.currentTarget.style.color = '#1a1512' }}
            onMouseLeave={e => { e.currentTarget.style.background = 'transparent'; e.currentTarget.style.color = '#a89f98' }}
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* ── Scrollable body ── */}
        <div className="overflow-y-auto flex-1 px-6 py-5 space-y-5">

          {/* This report */}
          <div className="flex items-center gap-3 px-4 py-3.5 rounded-xl"
               style={{ background: 'rgba(77,14,56,0.05)', border: '1.5px solid rgba(77,14,56,0.12)' }}>
            <CheckSquare className="w-4 h-4 flex-shrink-0" style={{ color: '#4d0e38' }} />
            <div className="flex-1 min-w-0">
              <div className="font-bold text-sm" style={{ color: '#4d0e38' }}>
                {report?.department?.name ?? 'Your Department'}
              </div>
              <div className="text-xs font-medium mt-0.5" style={{ color: '#7a7068' }}>
                {report?.notes.length ?? 0} activity point(s) · {formatDate(weekendDate, 'dd MMM yyyy')}
              </div>
            </div>
            <span className="badge badge-spr">Included</span>
          </div>

          {/* Other departments */}
          <div>
            <button
              type="button"
              onClick={() => setShowOther(v => !v)}
              className="w-full flex items-center justify-between px-4 py-3 rounded-xl transition-all duration-150"
              style={{
                border:     '1px solid #ece8e5',
                background: showOther ? 'rgba(77,14,56,0.03)' : '#faf9f8',
              }}
            >
              <div className="flex items-center gap-2.5">
                <Building2 className="w-4 h-4" style={{ color: '#a89f98' }} />
                <span className="font-semibold text-sm" style={{ color: '#1a1512' }}>
                  Add other departments
                </span>
                {selectedOtherIds.length > 0 && (
                  <span className="badge badge-green">{selectedOtherIds.length} added</span>
                )}
              </div>
              {showOther
                ? <ChevronUp   className="w-4 h-4" style={{ color: '#a89f98' }} />
                : <ChevronDown className="w-4 h-4" style={{ color: '#a89f98' }} />}
            </button>

            {showOther && (
              <div className="mt-2 rounded-xl overflow-hidden"
                   style={{ border: '1px solid #ece8e5' }}>
                {otherReports.length === 0 ? (
                  <div className="px-4 py-5 text-center">
                    <p className="text-sm font-medium" style={{ color: '#a89f98' }}>
                      No other departments have published a report for this week yet.
                    </p>
                  </div>
                ) : otherReports.map((r, i) => {
                  const sel = selectedOtherIds.includes(r.id)
                  return (
                    <button key={r.id} type="button" onClick={() => toggleOther(r.id)}
                      className="w-full flex items-center gap-3 px-4 py-3.5 text-left transition-colors"
                      style={{
                        borderTop:  i > 0 ? '1px solid #f0ece8' : 'none',
                        background: sel ? 'rgba(34,197,94,0.05)' : 'transparent',
                      }}
                      onMouseEnter={e => { if (!sel) e.currentTarget.style.background = '#faf9f8' }}
                      onMouseLeave={e => { if (!sel) e.currentTarget.style.background = sel ? 'rgba(34,197,94,0.05)' : 'transparent' }}
                    >
                      {sel
                        ? <CheckSquare className="w-4 h-4 flex-shrink-0" style={{ color: '#16a34a' }} />
                        : <Square      className="w-4 h-4 flex-shrink-0" style={{ color: '#d4cec8' }} />}
                      <div className="flex-1 min-w-0">
                        <div className="font-bold text-sm" style={{ color: sel ? '#15803d' : '#1a1512' }}>
                          {r.department?.name}
                        </div>
                        <div className="text-xs font-medium mt-0.5" style={{ color: '#a89f98' }}>
                          {r.notes.length} point(s) · {r.user?.username}
                        </div>
                      </div>
                      {sel && <span className="badge badge-green">Added</span>}
                    </button>
                  )
                })}
              </div>
            )}
          </div>

          {/* What Outlook will open with */}
          <div className="rounded-xl overflow-hidden"
               style={{ border: '1px solid #ece8e5' }}>
            <div className="px-4 py-2.5 flex items-center gap-2"
                 style={{ background: '#4d0e38' }}>
              <Mail className="w-3.5 h-3.5 flex-shrink-0" style={{ color: 'rgba(255,255,255,0.7)' }} />
              <span className="text-xs font-bold tracking-wide" style={{ color: 'rgba(255,255,255,0.85)' }}>
                OUTLOOK WILL OPEN WITH
              </span>
            </div>
            <div className="px-4 py-3.5 space-y-2.5" style={{ background: '#faf9f8' }}>
              <div className="flex items-start gap-3">
                <span className="text-[10px] font-black uppercase tracking-widest mt-0.5 w-14 flex-shrink-0"
                      style={{ color: '#a89f98' }}>Subject</span>
                <span className="text-xs font-semibold leading-relaxed" style={{ color: '#1a1512' }}>
                  SPR India — Weekly Activity Report | Week Ending {formatDate(weekendDate, 'dd MMMM yyyy')}
                </span>
              </div>
              <div className="flex items-start gap-3">
                <span className="text-[10px] font-black uppercase tracking-widest mt-0.5 w-14 flex-shrink-0"
                      style={{ color: '#a89f98' }}>Body</span>
                <span className="text-xs font-medium" style={{ color: '#7a7068' }}>
                  {allSelected.length} department{allSelected.length !== 1 ? 's' : ''} ·{' '}
                  {allSelected.reduce((s, r) => s + r.notes.length, 0)} activity point(s) pre-filled
                </span>
              </div>
              <div className="flex items-start gap-3">
                <span className="text-[10px] font-black uppercase tracking-widest mt-0.5 w-14 flex-shrink-0"
                      style={{ color: '#a89f98' }}>To / CC</span>
                <span className="text-xs font-medium" style={{ color: '#7a7068' }}>
                  Add recipients directly in Outlook before sending
                </span>
              </div>
            </div>
          </div>

        </div>

        {/* ── Footer ── */}
        <div className="px-6 py-5 space-y-2.5"
             style={{ borderTop: '1px solid #f0ece8', flexShrink: 0 }}>
          <button
            type="button"
            onClick={handleOpenOutlook}
            className="btn btn-primary w-full btn-lg"
          >
            <Send className="w-4 h-4" />
            Open in Outlook
          </button>
          <p className="text-center text-xs font-medium" style={{ color: '#a89f98' }}>
            Outlook opens directly on your desktop with the report already filled in
          </p>
          <button type="button" onClick={onClose}
                  className="btn btn-ghost w-full" style={{ color: '#a89f98' }}>
            Cancel
          </button>
        </div>

      </div>
    </div>
  )
}
