"""
Professional PDF generator — SPR Weekly Report Management Hub.

Format per department:
  ┌──────────────────────────────────────────┐
  │  WEEKLY REPORT   Generated by SPR Hub   │
  ├──────────────────────────────────────────┤
  │  Department | Name | Week Date           │
  ├────┬─────────────────────────────────────┤
  │ #  │  Report Details                     │
  ├────┼─────────────────────────────────────┤
  │ 1  │  Activity text…                     │
  │    │  [image if linked to this point]    │
  ├────┼─────────────────────────────────────┤
  │ 2  │  Next activity…                     │
  └────┴─────────────────────────────────────┘
"""
from io import BytesIO
from datetime import datetime
from pathlib import Path
from typing import List

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    Image as RLImage, HRFlowable, PageBreak, KeepTogether
)
from reportlab.pdfgen import canvas as pdfcanvas

# ── Brand palette ──────────────────────────────────────────────────────────────
NAVY        = colors.HexColor("#1e3a5f")
BLUE        = colors.HexColor("#2563eb")
LIGHT_BLUE  = colors.HexColor("#dbeafe")
GRAY_100    = colors.HexColor("#f3f4f6")
GRAY_200    = colors.HexColor("#e5e7eb")
GRAY_500    = colors.HexColor("#6b7280")
GRAY_800    = colors.HexColor("#1f2937")
WHITE       = colors.white

PAGE_W, PAGE_H = A4
L_MARGIN = R_MARGIN = 1.8 * cm
T_MARGIN = 1.8 * cm
B_MARGIN = 2.4 * cm
CONTENT_W = PAGE_W - L_MARGIN - R_MARGIN


# ── Paragraph styles ───────────────────────────────────────────────────────────
def _S():
    return {
        "hdr_title": ParagraphStyle("HT", fontName="Helvetica-Bold", fontSize=16,
                                    textColor=WHITE, alignment=TA_CENTER),
        "hdr_sub":   ParagraphStyle("HS", fontName="Helvetica", fontSize=9,
                                    textColor=colors.HexColor("#bfdbfe"), alignment=TA_CENTER),
        "meta_lbl":  ParagraphStyle("ML", fontName="Helvetica-Bold", fontSize=9,
                                    textColor=GRAY_500),
        "meta_val":  ParagraphStyle("MV", fontName="Helvetica-Bold", fontSize=10,
                                    textColor=GRAY_800),
        "tbl_hdr":   ParagraphStyle("TH", fontName="Helvetica-Bold", fontSize=9,
                                    textColor=WHITE),
        "num":       ParagraphStyle("NUM", fontName="Helvetica-Bold", fontSize=10,
                                    textColor=BLUE, alignment=TA_CENTER),
        "body":      ParagraphStyle("BODY", fontName="Helvetica", fontSize=10,
                                    textColor=GRAY_800, leading=15),
        "caption":   ParagraphStyle("CAP", fontName="Helvetica-Oblique", fontSize=8,
                                    textColor=GRAY_500, alignment=TA_CENTER),
        "toc_body":  ParagraphStyle("TOC", fontName="Helvetica", fontSize=9,
                                    textColor=GRAY_800, leading=14),
        "footer":    ParagraphStyle("FT", fontName="Helvetica", fontSize=8,
                                    textColor=GRAY_500, alignment=TA_CENTER),
        "divider_lbl": ParagraphStyle("DL", fontName="Helvetica-Bold", fontSize=8,
                                      textColor=GRAY_500, alignment=TA_CENTER),
        "dept_title": ParagraphStyle("DPT", fontName="Helvetica-Bold", fontSize=12,
                                     textColor=NAVY),
    }


# ── Numbered canvas ────────────────────────────────────────────────────────────
class _NC(pdfcanvas.Canvas):
    def __init__(self, *a, **kw):
        super().__init__(*a, **kw)
        self._pages: list = []

    def showPage(self):
        self._pages.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        n = len(self._pages)
        for i, st in enumerate(self._pages, 1):
            self.__dict__.update(st)
            self._footer(i, n)
            pdfcanvas.Canvas.showPage(self)
        pdfcanvas.Canvas.save(self)

    def _footer(self, num: int, total: int):
        self.saveState()
        self.setStrokeColor(GRAY_200)
        self.setLineWidth(0.4)
        self.line(L_MARGIN, 1.6 * cm, PAGE_W - R_MARGIN, 1.6 * cm)
        self.setFont("Helvetica", 7.5)
        self.setFillColor(GRAY_500)
        gen = datetime.utcnow().strftime("%d %b %Y, %H:%M UTC")
        self.drawString(L_MARGIN, 1.2 * cm, f"Weekly Report — Generated by SPR Weekly Report Hub  |  {gen}")
        self.drawRightString(PAGE_W - R_MARGIN, 1.2 * cm, f"Page {num} / {total}")
        self.restoreState()


# ── Helper: safely load an image flowable ────────────────────────────────────
def _load_image(fp: str, max_w: float, max_h: float):
    """Returns a centred RLImage or None."""
    try:
        p = Path(fp)
        if not p.exists():
            return None
        img = RLImage(str(p))
        iw, ih = img.imageWidth, img.imageHeight
        if iw <= 0 or ih <= 0:
            return None
        ratio = min(max_w / iw, max_h / ih, 1.0)
        img.drawWidth  = iw * ratio
        img.drawHeight = ih * ratio
        img.hAlign = "CENTER"
        return img
    except Exception:
        return None


# ── Build the header banner for the whole document ────────────────────────────
def _doc_header(styles):
    rows = [
        [Paragraph("WEEKLY REPORT", styles["hdr_title"])],
        [Paragraph("Generated by SPR Weekly Report Management Hub", styles["hdr_sub"])],
    ]
    tbl = Table(rows, colWidths=[CONTENT_W])
    tbl.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), NAVY),
        ("ALIGN",         (0, 0), (-1, -1), "CENTER"),
        ("TOPPADDING",    (0, 0), (-1, -1), 14),
        ("BOTTOMPADDING", (0, -1), (-1, -1), 14),
    ]))
    return tbl


# ── Meta block: Dept / Name / Week Date ───────────────────────────────────────
def _meta_block(dept: str, name: str, week_date: str, styles):
    data = [[
        Table([[Paragraph("Department", styles["meta_lbl"])],
               [Paragraph(dept, styles["meta_val"])]],
              colWidths=[(CONTENT_W - 2 * cm) / 3]),
        Table([[Paragraph("Prepared by", styles["meta_lbl"])],
               [Paragraph(name, styles["meta_val"])]],
              colWidths=[(CONTENT_W - 2 * cm) / 3]),
        Table([[Paragraph("Week Date", styles["meta_lbl"])],
               [Paragraph(week_date, styles["meta_val"])]],
              colWidths=[(CONTENT_W - 2 * cm) / 3]),
    ]]
    tbl = Table(data, colWidths=[(CONTENT_W) / 3] * 3)
    tbl.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), LIGHT_BLUE),
        ("BOX",           (0, 0), (-1, -1), 0.5, colors.HexColor("#93c5fd")),
        ("INNERGRID",     (0, 0), (-1, -1), 0.3, colors.HexColor("#bfdbfe")),
        ("TOPPADDING",    (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("LEFTPADDING",   (0, 0), (-1, -1), 12),
    ]))
    return tbl


# ── Build the main report details table for one department ───────────────────
def _report_table(notes: list, images_by_note: dict, loose_images: list, styles):
    """
    notes            – list of {content, order_index}
    images_by_note   – {note_id: [image_dicts]}
    loose_images     – images not linked to any note
    """
    NUM_W   = 1.2 * cm
    BODY_W  = CONTENT_W - NUM_W
    IMG_MAX_W = BODY_W - 0.8 * cm
    IMG_MAX_H = 9 * cm

    # Header row
    table_data = [[
        Paragraph("#", styles["tbl_hdr"]),
        Paragraph("Report Details", styles["tbl_hdr"]),
    ]]
    style_cmds = [
        ("BACKGROUND",    (0, 0), (-1, 0), NAVY),
        ("TEXTCOLOR",     (0, 0), (-1, 0), WHITE),
        ("ALIGN",         (0, 0), (0, -1), "CENTER"),
        ("VALIGN",        (0, 0), (-1, -1), "TOP"),
        ("FONTSIZE",      (0, 0), (-1, -1), 9),
        ("TOPPADDING",    (0, 0), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ("LEFTPADDING",   (0, 0), (-1, -1), 8),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 8),
        ("LINEBELOW",     (0, 0), (-1, -1), 0.3, GRAY_200),
        ("BOX",           (0, 0), (-1, -1), 0.5, GRAY_200),
    ]

    for row_i, note in enumerate(notes, 1):
        row_idx = len(table_data)
        # Alternate row background
        bg = WHITE if row_i % 2 == 1 else GRAY_100
        style_cmds.append(("BACKGROUND", (0, row_idx), (-1, row_idx), bg))

        table_data.append([
            Paragraph(str(row_i), styles["num"]),
            Paragraph(note["content"].replace("\n", "<br/>"), styles["body"]),
        ])

        # Images linked to this note
        linked = images_by_note.get(note.get("id"), [])
        for img_data in sorted(linked, key=lambda x: x.get("order_index", 0)):
            img = _load_image(img_data.get("file_path", ""), IMG_MAX_W, IMG_MAX_H)
            if img:
                cap = img_data.get("caption") or img_data.get("original_name", "")
                img_row_idx = len(table_data)
                style_cmds.append(("BACKGROUND", (0, img_row_idx), (-1, img_row_idx), bg))
                style_cmds.append(("SPAN",       (0, img_row_idx), (-1, img_row_idx)))
                content = [img]
                if cap:
                    content.append(Paragraph(cap, styles["caption"]))
                # Wrap in a mini-table centered
                inner = Table([[c] for c in content], colWidths=[CONTENT_W - 0.5 * cm])
                inner.setStyle(TableStyle([
                    ("ALIGN",  (0, 0), (-1, -1), "CENTER"),
                    ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ]))
                table_data.append([inner, ""])   # "" fills the SPAN'd cell

    # Loose images (not linked to any note) — span full width at bottom
    if loose_images:
        sep_idx = len(table_data)
        style_cmds.append(("SPAN",       (0, sep_idx), (-1, sep_idx)))
        style_cmds.append(("BACKGROUND", (0, sep_idx), (-1, sep_idx), LIGHT_BLUE))
        table_data.append([Paragraph("Additional Attachments", styles["tbl_hdr"]), ""])

        for img_data in sorted(loose_images, key=lambda x: x.get("order_index", 0)):
            img = _load_image(img_data.get("file_path", ""), IMG_MAX_W, IMG_MAX_H)
            if img:
                cap = img_data.get("caption") or img_data.get("original_name", "")
                r_idx = len(table_data)
                style_cmds.append(("SPAN",       (0, r_idx), (-1, r_idx)))
                style_cmds.append(("BACKGROUND", (0, r_idx), (-1, r_idx), GRAY_100))
                inner = Table([[img]] + ([[Paragraph(cap, styles["caption"])]] if cap else []),
                              colWidths=[CONTENT_W - 0.5 * cm])
                inner.setStyle(TableStyle([("ALIGN", (0,0),(-1,-1),"CENTER")]))
                table_data.append([inner, ""])

    tbl = Table(table_data, colWidths=[NUM_W, BODY_W], repeatRows=1)
    tbl.setStyle(TableStyle(style_cmds))
    return tbl


# ── Section divider between departments ───────────────────────────────────────
def _dept_divider(styles):
    tbl = Table(
        [[Paragraph("─" * 60, styles["divider_lbl"])]],
        colWidths=[CONTENT_W],
    )
    tbl.setStyle(TableStyle([
        ("ALIGN",  (0,0),(-1,-1), "CENTER"),
        ("TOPPADDING",    (0,0),(-1,-1), 6),
        ("BOTTOMPADDING", (0,0),(-1,-1), 6),
    ]))
    return tbl


# ── Main entry point ───────────────────────────────────────────────────────────
def generate_pdf(reports_data: list) -> bytes:
    """
    reports_data: list of dicts:
        department_name  (str)
        department_code  (str)
        weekend_date     (str, e.g. "2026-06-07")
        user_name        (str)
        notes            list of {id, content, order_index}
        images           list of {file_path, caption, original_name, order_index, note_id}
    """
    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=L_MARGIN, rightMargin=R_MARGIN,
        topMargin=T_MARGIN, bottomMargin=B_MARGIN,
        title="SPR Weekly Report",
    )
    styles  = _S()
    elems   = []

    # ── Document header (once) ─────────────────────────────────────────────
    elems.append(_doc_header(styles))
    elems.append(Spacer(1, 0.5 * cm))

    # ── TOC for multi-dept ─────────────────────────────────────────────────
    if len(reports_data) > 1:
        toc_rows = [[
            Paragraph("<b>Department</b>", styles["tbl_hdr"]),
            Paragraph("<b>Prepared by</b>", styles["tbl_hdr"]),
            Paragraph("<b>Week Date</b>", styles["tbl_hdr"]),
            Paragraph("<b>Activities</b>", styles["tbl_hdr"]),
        ]]
        for r in reports_data:
            toc_rows.append([
                Paragraph(r["department_name"], styles["toc_body"]),
                Paragraph(r["user_name"], styles["toc_body"]),
                Paragraph(r["weekend_date"], styles["toc_body"]),
                Paragraph(str(len(r["notes"])), styles["toc_body"]),
            ])
        cw = CONTENT_W / 4
        toc = Table(toc_rows, colWidths=[cw * 1.4, cw * 1.2, cw * 0.9, cw * 0.5])
        toc.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, 0), NAVY),
            ("ROWBACKGROUNDS",(0, 1), (-1, -1), [WHITE, GRAY_100]),
            ("GRID",          (0, 0), (-1, -1), 0.3, GRAY_200),
            ("TOPPADDING",    (0, 0), (-1, -1), 7),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
            ("LEFTPADDING",   (0, 0), (-1, -1), 8),
            ("FONTSIZE",      (0, 0), (-1, -1), 9),
        ]))
        elems.append(toc)
        elems.append(Spacer(1, 0.5 * cm))

    # ── One section per department ─────────────────────────────────────────
    for idx, r in enumerate(reports_data):
        if idx > 0:
            elems.append(PageBreak())

        dept       = r.get("department_name", "—")
        user       = r.get("user_name", "—")
        week_date  = r.get("weekend_date", "—")
        notes      = sorted(r.get("notes", []), key=lambda x: x.get("order_index", 0))
        images     = r.get("images", [])

        # Partition images: linked to a note vs loose
        images_by_note: dict = {}
        loose: list = []
        for img in images:
            nid = img.get("note_id")
            if nid:
                images_by_note.setdefault(nid, []).append(img)
            else:
                loose.append(img)

        # Meta block
        elems.append(_meta_block(dept, user, week_date, styles))
        elems.append(Spacer(1, 0.35 * cm))

        # Report details table
        if notes:
            rpt_tbl = _report_table(notes, images_by_note, loose, styles)
            elems.append(rpt_tbl)
        else:
            # Empty placeholder
            ph = Table([[Paragraph("No activities recorded for this period.", styles["body"])]],
                       colWidths=[CONTENT_W])
            ph.setStyle(TableStyle([
                ("BOX",           (0,0),(-1,-1), 0.5, GRAY_200),
                ("TOPPADDING",    (0,0),(-1,-1), 16),
                ("BOTTOMPADDING", (0,0),(-1,-1), 16),
                ("ALIGN",         (0,0),(-1,-1), "CENTER"),
            ]))
            elems.append(ph)

    doc.build(elems, canvasmaker=_NC)
    return buf.getvalue()
